stages:
  - version
  - release

workflow:
  rules:
    - if: $CI_COMMIT_TAG == null

get-version:
  stage: version
  image: mcr.microsoft.com/dotnet/sdk:5.0-alpine3.12
  # rules:
  #   - if: $CI_COMMIT_BRANCH
  before_script:
    - echo 'running generate version'
    - export PATH="$PATH:/root/.dotnet/tools"
  script:
    - export
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_BRANCH
    # - dotnet tool install -g Passingwind.Git-CI-Tools --version 0.1.0-pre.3
    # - gitci version current -o $CI_PROJECT_DIR/variables.env --format dotenv --include-prerelease
    # - gitci version next --branch="origin/${CI_COMMIT_REF_NAME}" -o $CI_PROJECT_DIR/variables.env --format dotenv --include-prerelease  --prerelease="dev" --build=$CI_COMMIT_SHORT_SHA  --debug-mode
    # - gitci release notes --branch="origin/${CI_COMMIT_REF_NAME}" -o $CI_PROJECT_DIR/CHANGELOG.md  --include-prerelease=false
    #
    - cd Git-CI-Tools
    - dotnet restore
    #
    - dotnet run -- version current -o $CI_PROJECT_DIR/variables.env --format dotenv
    #
    - dotnet run -- version next --branch "origin/feature/gitlab" -o $CI_PROJECT_DIR/variables.env --format dotenv --include-prerelease  --prerelease-ver="dev.${CI_PIPELINE_ID}" --build-ver="$CI_COMMIT_SHORT_SHA"  --debug-mode
    #
    - dotnet run -- release changes --branch "origin/feature/gitlab" -o $CI_PROJECT_DIR/CHANGELOG.md  --include-prerelease=false
    #
    - ls $CI_PROJECT_DIR

    # 
    - cat $CI_PROJECT_DIR/variables.env
  artifacts: 
    paths:
      - CHANGELOG.md
    reports: 
      dotenv: variables.env

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  # rules:
  # - if: $CI_COMMIT_TAG
  #   when: never # Do not run this job when a tag is created manually
  # - if: $CI_COMMIT_BRANCH
  # - if: $NEXT_VERSION
  needs:
    - job: get-version
      artifacts: true
  script:
    - echo "running release job for $NEXT_VERSION"
  release:
    tag_name: "v$NEXT_VERSION"
    description: CHANGELOG.md
    ref: "$CI_COMMIT_SHA"
    name: "Release $NEXT_VERSION"
