version-resolver:
  major:
    commits:
      - "Major"
      - "[break changes]" 
      - "break" 
    labels:
      - "Versioning - major"
  minor:
    commits:
      - "[feat]"
      - "[minor]"
      - "feat"
      - ":bulb:"
    labels:
      - "Versioning - Minor"
  patch:
    commits:
      - "[fix]"
      - "[fix bugs]"
      - "fix"
      - ":zap:"
      - ":bug:"
    labels:
      - "Versioning - Patch"
  default: patch

categories:
  - title: "🌈 Breaking Changes"
    labels:
      - "Feature"
    commits:
      - "[break]"
  - title: "🚀 Features"
    labels:
      - "Feature"
    commits:
      - "[feat]"
      - "feat"
      - ":bulb:"
  - title: "🐛 Bug Fixes"
    labels:
      - "Bug - Fixed"
      - "Fix"
    commits:
      - "[fix]"
      - "[fix bugs]"
      - "fix"
      - ":zap:"
      - ":bug:"
  - title: "📖 Documentation"
    labels:
      - "Documentation"
    commits:
      - "[docs]"
      - "docs"
      - ":memo:"
  - title: "🧰 Maintenance"
    labels:
      - "Chore"
      - "Maintenance"

template: |
  ## Changes
  Contributors: $CONTRIBUTORS
  $CHANGES
